-- =========================================================================
-- MIGRATION V1: SCHEMA INICIAL CORPORATIVO (OPERACAO APROVACAO)
-- Compativel com PostgreSQL e H2 Database
-- =========================================================================

-- Tabela de Usuarios e Autenticacao
CREATE TABLE tb_usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'ROLE_STUDENT',
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- Tabela de Bancas Examinadoras
CREATE TABLE tb_banca (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    sigla VARCHAR(50) NOT NULL UNIQUE,
    site_oficial VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- Tabela de Concursos Publicos
CREATE TABLE tb_concurso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    banca_id BIGINT NOT NULL,
    orgao VARCHAR(150) NOT NULL,
    estado VARCHAR(2),
    ano INT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PREVISTO',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_concurso_banca FOREIGN KEY (banca_id) REFERENCES tb_banca (id)
);

-- Tabela de Editais
CREATE TABLE tb_edital (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concurso_id BIGINT NOT NULL,
    numero VARCHAR(100) NOT NULL,
    data_publicacao DATE,
    link_oficial VARCHAR(500),
    total_vagas INT,
    total_questoes INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_edital_concurso FOREIGN KEY (concurso_id) REFERENCES tb_concurso (id)
);

-- Tabela de Disciplinas
CREATE TABLE tb_disciplina (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL UNIQUE,
    codigo VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- Tabela de Assuntos (Subtopicos por Disciplina)
CREATE TABLE tb_assunto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disciplina_id BIGINT NOT NULL,
    nome VARCHAR(200) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_assunto_disciplina FOREIGN KEY (disciplina_id) REFERENCES tb_disciplina (id)
);

-- Cargas iniciais de semente (Seed inicial de Bancas)
INSERT INTO tb_banca (nome, sigla, site_oficial) VALUES 
('Centro Brasileiro de Pesquisa em Avaliacao e Selecao e de Promocao de Eventos', 'CEBRASPE', 'https://www.cebraspe.org.br'),
('Fundacao Getulio Vargas', 'FGV', 'https://conhecimento.fgv.br/concursos'),
('Fundacao Carlos Chagas', 'FCC', 'https://www.concursosfcc.com.br');

-- Seed inicial de Concursos
INSERT INTO tb_concurso (banca_id, orgao, estado, ano, status) VALUES 
(1, 'Policia Civil do Estado de Pernambuco', 'PE', 2024, 'HOMOLOGADO'),
(1, 'Policia Civil do Estado de Pernambuco', 'PE', 2027, 'EDITAL_IMINENTE');
