-- =========================================================================
-- MIGRATION V2: MOTOR DE QUESTOES & ITENS CEBRASPE (OPERACAO APROVACAO)
-- Compativel com PostgreSQL e H2 Database
-- =========================================================================

-- Tabela de Questoes (Suporta Certo/Errado e Multipla Escolha)
CREATE TABLE tb_questao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    banca_id BIGINT NOT NULL,
    concurso_id BIGINT,
    disciplina_id BIGINT NOT NULL,
    assunto_id BIGINT NOT NULL,
    enunciado TEXT NOT NULL,
    texto_base TEXT,
    tipo VARCHAR(30) NOT NULL DEFAULT 'CERTO_ERRADO',
    dificuldade VARCHAR(20) NOT NULL DEFAULT 'MEDIA',
    ano INT NOT NULL,
    anulada BOOLEAN NOT NULL DEFAULT FALSE,
    gabarito_oficial VARCHAR(10) NOT NULL,
    justificativa TEXT,
    fundamentacao_legal TEXT,
    jurisprudencia TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_questao_banca FOREIGN KEY (banca_id) REFERENCES tb_banca (id),
    CONSTRAINT fk_questao_concurso FOREIGN KEY (concurso_id) REFERENCES tb_concurso (id),
    CONSTRAINT fk_questao_disciplina FOREIGN KEY (disciplina_id) REFERENCES tb_disciplina (id),
    CONSTRAINT fk_questao_assunto FOREIGN KEY (assunto_id) REFERENCES tb_assunto (id)
);

-- Tabela de Alternativas (Itens A, B, C, D, E para Questoes de Multipla Escolha)
CREATE TABLE tb_alternativa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    questao_id BIGINT NOT NULL,
    letra VARCHAR(5) NOT NULL,
    texto TEXT NOT NULL,
    correta BOOLEAN NOT NULL DEFAULT FALSE,
    explicacao TEXT,
    CONSTRAINT fk_alternativa_questao FOREIGN KEY (questao_id) REFERENCES tb_questao (id) ON DELETE CASCADE
);

-- Indices B-Tree para Filtros de Busca em Milissegundos
CREATE INDEX idx_questao_banca ON tb_questao(banca_id);
CREATE INDEX idx_questao_concurso ON tb_questao(concurso_id);
CREATE INDEX idx_questao_disciplina ON tb_questao(disciplina_id);
CREATE INDEX idx_questao_assunto ON tb_questao(assunto_id);
CREATE INDEX idx_questao_ano ON tb_questao(ano);
CREATE INDEX idx_alternativa_questao ON tb_alternativa(questao_id);

-- Carga Inicial (Seed): Disciplinas e Assuntos Oficiais da PC-PE
INSERT INTO tb_disciplina (nome, codigo) VALUES 
('Lingua Portuguesa', 'PORT'),
('Direito Penal', 'DPEN'),
('Direito Processual Penal', 'DPPR');

INSERT INTO tb_assunto (disciplina_id, nome) VALUES 
(1, 'Interpretacao e Compreensao de Texto'),
(1, 'Concordancia Verbal e Nominal'),
(2, 'Crimes contra a Pessoa (Homicidio e Lesao Corporal)'),
(2, 'Crimes contra o Patrimonio (Furto e Roubo)'),
(3, 'Inquerito Policial (Caracteristicas e Prazos)'),
(3, 'Prisao em Flagrante e Prisao Preventiva');

-- Seed Inicial de Questoes Reais do Cebraspe para PC-PE
INSERT INTO tb_questao (
    banca_id, concurso_id, disciplina_id, assunto_id,
    enunciado, texto_base, tipo, dificuldade, ano, anulada,
    gabarito_oficial, justificativa, fundamentacao_legal, jurisprudencia
) VALUES 
(
    1, 1, 3, 5,
    'O inquerito policial possui natureza de procedimento administrativo inquisitivo e informativo, razao pela qual eventuais irregularidades ocorridas durante a sua realizacao nao possuem o condao de anular o processo judicial subsequente.',
    NULL, 'CERTO_ERRADO', 'MEDIA', 2024, FALSE,
    'CERTO',
    'Item correto. A doutrina e a jurisprudencia pacifica dos tribunais superiores entendem que o inquerito policial e mero procedimento informativo. Vicios na fase policial nao contaminam a acao penal subsequente.',
    'Art. 4º ao 23 do Codigo de Processo Penal (CPP).',
    'Jurisprudencia consolidada do STF (RHC 131.428) e STJ (HC 478.112).'
),
(
    1, 1, 2, 3,
    'No homicidio culposo praticado na conducao de veiculo automotor, a pena e aumentada de um terco a metade se o agente nao possuir permissao para dirigir ou carteira de habilitacao.',
    NULL, 'CERTO_ERRADO', 'FACIL', 2024, FALSE,
    'CERTO',
    'Item correto. Trata-se de causa de aumento de pena expressamente prevista no Codigo de Transito Brasileiro aplicada em concursos policiais.',
    'Art. 302, § 1º, inciso I do Codigo de Transito Brasileiro (Lei nº 9.503/1997).',
    'Informativo de Jurisprudencia do STJ.'
);
