-- =========================================================================
-- MIGRATION V3: MOTOR DE SIMULADOS & TELEMETRIA CEBRASPE (OPERACAO APROVACAO)
-- Compativel com PostgreSQL e H2 Database
-- =========================================================================

-- Tabela de Simulados de Prova
CREATE TABLE tb_simulado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    descricao TEXT,
    concurso_id BIGINT,
    modo VARCHAR(30) NOT NULL DEFAULT 'PROVA_COMPLETA',
    tempo_limite_minutos INT NOT NULL DEFAULT 270,
    total_questoes INT NOT NULL DEFAULT 60,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_simulado_concurso FOREIGN KEY (concurso_id) REFERENCES tb_concurso (id)
);

-- Tabela de Itens do Simulado (Ordenacao de Questoes na Grade da Prova)
CREATE TABLE tb_item_simulado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    simulado_id BIGINT NOT NULL,
    questao_id BIGINT NOT NULL,
    numero_questao INT NOT NULL,
    peso NUMERIC(4,2) NOT NULL DEFAULT 1.00,
    CONSTRAINT fk_item_simulado FOREIGN KEY (simulado_id) REFERENCES tb_simulado (id) ON DELETE CASCADE,
    CONSTRAINT fk_item_questao FOREIGN KEY (questao_id) REFERENCES tb_questao (id) ON DELETE CASCADE,
    CONSTRAINT uk_item_simulado_numero UNIQUE (simulado_id, numero_questao)
);

-- Tabela de Tentativas do Aluno (Sessao de Prova com Telemetria e Resultado)
CREATE TABLE tb_tentativa_simulado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    simulado_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'EM_ANDAMENTO',
    data_inicio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_fim TIMESTAMP,
    tempo_total_segundos INT,
    pontuacao_liquida NUMERIC(6,2),
    total_acertos INT DEFAULT 0,
    total_erros INT DEFAULT 0,
    total_em_branco INT DEFAULT 0,
    total_anuladas INT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_tentativa_usuario FOREIGN KEY (usuario_id) REFERENCES tb_usuario (id) ON DELETE CASCADE,
    CONSTRAINT fk_tentativa_simulado FOREIGN KEY (simulado_id) REFERENCES tb_simulado (id) ON DELETE CASCADE
);

-- Tabela de Respostas do Aluno por Questao (Marcacoes, Telemetria de Tempo e Pontos Cebraspe)
CREATE TABLE tb_resposta_tentativa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tentativa_id BIGINT NOT NULL,
    questao_id BIGINT NOT NULL,
    resposta_marcada VARCHAR(10),
    tempo_gasto_segundos INT DEFAULT 0,
    correta BOOLEAN,
    pontos_atribuidos NUMERIC(4,2) DEFAULT 0.00,
    CONSTRAINT fk_resposta_tentativa FOREIGN KEY (tentativa_id) REFERENCES tb_tentativa_simulado (id) ON DELETE CASCADE,
    CONSTRAINT fk_resposta_questao FOREIGN KEY (questao_id) REFERENCES tb_questao (id) ON DELETE CASCADE,
    CONSTRAINT uk_resposta_tentativa_questao UNIQUE (tentativa_id, questao_id)
);

-- Indices B-Tree para Relatorios Estatisticos e Consultas de Alto Desempenho
CREATE INDEX idx_item_simulado ON tb_item_simulado(simulado_id);
CREATE INDEX idx_item_questao ON tb_item_simulado(questao_id);
CREATE INDEX idx_tentativa_usuario ON tb_tentativa_simulado(usuario_id);
CREATE INDEX idx_tentativa_simulado ON tb_tentativa_simulado(simulado_id);
CREATE INDEX idx_tentativa_status ON tb_tentativa_simulado(status);
CREATE INDEX idx_resposta_tentativa ON tb_resposta_tentativa(tentativa_id);
CREATE INDEX idx_resposta_questao ON tb_resposta_tentativa(questao_id);
